시퀀스들
seq_profile_no 
seq_tree_no
seq_forest_no
seq_tree_and_forest_no
seq_notice_message_no
seq_forest_notice_no
seq_event_no
seq_post_no
seq_image_and_like_no
seq_comment_no
seq_activity_point_no
seq_report_no
sqe_bucketlist_no

 DROP TABLE ACTIVITY_POINT;
 DROP TABLE BUCKETLIST;
 DROP TABLE CALENDER;
 DROP TABLE COMMENTS;
 DROP TABLE FOREST;
 DROP TABLE FOREST_NOTICE;
 DROP TABLE IMAGE_AND_LIKE;
 DROP TABLE NOTICE_MESSAGE;
 DROP TABLE POST;
 DROP TABLE PROFILES;
 DROP TABLE REPORT;
 DROP TABLE TREE;
 DROP TABLE TREE_ADDRESS;
 DROP TABLE TREE_FOREST;
 DROP TABLE TREE_IMAGE;
 DROP TABLE USERS;
 

CREATE SEQUENCE   "SEQ_ACTIVITY_POINT_NO"   INCREMENT BY 1 START WITH 1 ;

CREATE SEQUENCE   "SEQ_COMMENT_NO"   INCREMENT BY 1 START WITH 1 ;

CREATE SEQUENCE   "SEQ_EVENT_NO"   INCREMENT BY 1 START WITH 1 ;

CREATE SEQUENCE   "SEQ_FOREST_NO"   INCREMENT BY 1 START WITH 1 ;

CREATE SEQUENCE   "SEQ_FOREST_NOTICE_NO"   INCREMENT BY 1 START WITH 1 ;

CREATE SEQUENCE   "SEQ_IMAGE_AND_LIKE_NO"   INCREMENT BY 1 START WITH 1 ;

CREATE SEQUENCE   "SEQ_NOTICE_MESSAGE_NO"   INCREMENT BY 1 START WITH 1 ;

CREATE SEQUENCE   "SEQ_POST_NO"   INCREMENT BY 1 START WITH 1 ;

CREATE SEQUENCE   "SEQ_PROFILE_NO"   INCREMENT BY 1 START WITH 1 ;

CREATE SEQUENCE   "SEQ_REPORT_NO"   INCREMENT BY 1 START WITH 1 ;

CREATE SEQUENCE   "SEQ_TREE_AND_FOREST_NO"   INCREMENT BY 1 START WITH 1 ;

CREATE SEQUENCE   "SEQ_TREE_NO"   INCREMENT BY 1 START WITH 1 ;

CREATE SEQUENCE   "SQE_BUCKETLIST_NO"   INCREMENT BY 1 START WITH 1 ;


CREATE TABLE  "USERS" 
   (	"USER_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"TREE_NO" NUMBER, 
	"PASSWORD" VARCHAR2(30) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(30) NOT NULL ENABLE, 
	"USER_REG_DATE" DATE NOT NULL ENABLE, 
	"USER_WITHDRAW_REG_DATE" DATE, 
	"USER_STATE" CHAR(1) NOT NULL ENABLE, 
	"ROLE" VARCHAR2(5), 
	 CONSTRAINT "USERS_PK" PRIMARY KEY ("USER_ID") ENABLE, 
	 CONSTRAINT "USERS_CON" UNIQUE ("EMAIL") ENABLE
   );
   

   
   
   CREATE TABLE  "TREE" 
   (	"TREE_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"TREE_NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"COUNTRY_ID" CHAR(3) NOT NULL ENABLE, 
	"FAMILY_MOTTO" VARCHAR2(50), 
	"ACTIVITY_TOTAL_POINT" NUMBER(10,0) NOT NULL ENABLE, 
	"SEED_NO" CHAR(1) NOT NULL ENABLE, 
	"TREE_IMAGE_NAME" VARCHAR2(100), 
	 CONSTRAINT "TREE_PK" PRIMARY KEY ("TREE_NO") ENABLE
   );
   
   INSERT INTO tree values(SEQ_TREE_NO.nextval, '구본혁', '박박', 'kr', '차카게살자' , 0, '1', 'image.jpg' );
   INSERT INTO tree values(SEQ_TREE_NO.nextval, '구혁', '박박', 'kr', '차카게살자' , 0, '1', 'image.jpg' );
   
   
   CREATE TABLE  "PROFILES" 
   (	"PROFILE_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"TREE_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"PROFILE_STATE" CHAR(1) NOT NULL ENABLE, 
	"PROFILE_NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"PHONE" VARCHAR2(30), 
	"FAMILY_RELATIONS" VARCHAR2(30) NOT NULL ENABLE, 
	"PROFILE_IMAGE" VARCHAR2(100) NOT NULL ENABLE, 
	"BIRTHDAY" VARCHAR2(30), 
	"ADDRESS" VARCHAR2(100), 
	 CONSTRAINT "PROFILES_PK" PRIMARY KEY ("PROFILE_NO") ENABLE, 
	 CONSTRAINT "PROFILES_CON" FOREIGN KEY ("TREE_NO")
	  REFERENCES  "TREE" ("TREE_NO") ENABLE);
	  
	
	  INSERT INTO profiles values(SEQ_PROFILE_NO.nextval,23,'1','박길동','010-111-111','대장','~.jpg','1999-09-09','강남구');
	  
	CREATE TABLE  "TREE_IMAGE" 
   (	"TREE_IMAGE_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"SEED_NO" CHAR(1) NOT NULL ENABLE, 
	"TREE_IMAGE_NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"ACTIVITY_POINT_START" NUMBER(10,0) NOT NULL ENABLE, 
	"ACTIVITY_POINT_END" NUMBER(10,0) NOT NULL ENABLE
   );  
   
   INSERT INTO tree_image values(1,'1','뭉글뭉글',0,10);
   
   CREATE TABLE  "FOREST" 
   (	"FOREST_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"FOREST_NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"FOREST_CTREATER_TREE_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"INVITE_POSSIBLE_STATE" CHAR(1) NOT NULL ENABLE, 
	"FOREST_NAME_CHANGE_POSSIBLE_ST" CHAR(1) NOT NULL ENABLE, 
	"FOREST_INFORM_TEXT" VARCHAR2(1000), 
	"FOREST_INFORM_WRITER" VARCHAR2(30) NOT NULL ENABLE, 
	"FOREST_INFORM_REG_DATE" DATE NOT NULL ENABLE, 
	 CONSTRAINT "FOREST_PK" PRIMARY KEY ("FOREST_NO") ENABLE, 
	 CONSTRAINT "FOREST_UK1" UNIQUE ("FOREST_NAME") ENABLE
   );
   
   INSERT INTO FOREST values(SEQ_FOREST_NO.nextval,'조진우네숲',20001,'1','1','지누네는 따듯함','진우',SYSDATE);
   
   CREATE TABLE  "TREE_ADDRESS" 
   (	"COUNTRY_ID" CHAR(3) NOT NULL ENABLE, 
	"COUNTRY_NAME" VARCHAR2(30) NOT NULL ENABLE
   );
   
   INSERT INTO tree_address values('kor','korea');
   
   CREATE TABLE  "NOTICE_MESSAGE" 
   (	"NOTICE_MESSAGE_NO" NUMBER NOT NULL ENABLE, 
	"SENDER" VARCHAR2(30) NOT NULL ENABLE, 
	"RECEIVER" VARCHAR2(30) NOT NULL ENABLE, 
	"NOTICE_REG_DATE" DATE NOT NULL ENABLE, 
	"NOTICE_MESSAGE_STATE" CHAR(1) NOT NULL ENABLE, 
	"NOTICE_MESSAGE_TYPE" CHAR(1) NOT NULL ENABLE, 
	"NOTICE_MESSAGE_DETAIL" VARCHAR2(100), 
	"POST_IMAGE_NAME" VARCHAR2(30), 
	"NOTICE_MESSAGEBOX_STATE" CHAR(1) NOT NULL ENABLE, 
	"POST_NO" NUMBER, 
	"FOREST_NO" NUMBER, 
	"TREE_NO" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "NOTICE_MESSAGE_PK" PRIMARY KEY ("NOTICE_MESSAGE_NO") ENABLE, 
	 CONSTRAINT "NOTICE_MESSAGE_FK" FOREIGN KEY ("TREE_NO")
	  REFERENCES  "TREE" ("TREE_NO") ON DELETE CASCADE ENABLE
   );
   
   INSERT INTO NOTICE_MESSAGE values(SEQ_NOTICE_MESSAGE_NO.nextval,'진우','초아',SYSDATE,'1','1','초아누나가괴롭힌다.','나무','1',1,2,23);

   
   CREATE TABLE  "FOREST_NOTICE" 
   (	"FOREST_NOTICE_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"FOREST_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"FOREST_NOTICE_STATE" CHAR(1) NOT NULL ENABLE, 
	"FOREST_NOTICE_REG_DATE" DATE NOT NULL ENABLE, 
	 CONSTRAINT "FOREST_NOTICE_PK" PRIMARY KEY ("FOREST_NOTICE_NO") ENABLE
   );
   
    INSERT INTO FOREST_NOTICE values(SEQ_FOREST_NOTICE_NO.nextval,2,'1',SYSDATE);
    
    CREATE TABLE  "CALENDER" 
   (	"EVENT_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"TREE_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"EVENT_TITILE" VARCHAR2(30) NOT NULL ENABLE, 
	"EVENT_START_DATE" DATE NOT NULL ENABLE, 
	"EVENT_END_DATE" DATE NOT NULL ENABLE, 
	"D_DAY_STATE" CHAR(1), 
	"EVENT_DETAIL" VARCHAR2(200), 
	 CONSTRAINT "CALENDER_PK" PRIMARY KEY ("EVENT_NO") ENABLE, 
	 CONSTRAINT "CALENDER_FK" FOREIGN KEY ("TREE_NO")
	  REFERENCES  "TREE" ("TREE_NO") ON DELETE CASCADE ENABLE
   );
   
   SELECT * FROM    ALL_CONSTRAINTS
WHERE    TABLE_NAME = '테이블명';



   
   INSERT INTO CALENDER values(SEQ_EVENT_NO.nextval,23,'야',SYSDATE,SYSDATE,'1','짬봉먹자');
   
   CREATE TABLE  "POST" 
   (	"POST_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"POST_REG_DATE" DATE NOT NULL ENABLE, 
	"POST_DETAIL" VARCHAR2(500), 
	"POST_WRITER" VARCHAR2(30) NOT NULL ENABLE, 
	"POST_STATE" CHAR(1) NOT NULL ENABLE, 
	"TREE_NO" NUMBER(30,0) NOT NULL ENABLE, 
	"ALBUM_NAME" VARCHAR2(30), 
	 CONSTRAINT "POST_PK" PRIMARY KEY ("POST_NO") ENABLE, 
	 CONSTRAINT "POST_FK" FOREIGN KEY ("TREE_NO")
	  REFERENCES  "TREE" ("TREE_NO") ON DELETE CASCADE ENABLE
   );
   
    INSERT INTO POST values(SEQ_POST_NO.nextval,SYSDATE,'D','우씨','1',22,'흥');
    DELETE FROM POST WHERE tree_no = 21 ;
    DELETE FROM TREE WHERE tree_no = 22;
    
    CREATE TABLE  "IMAGE_AND_LIKE" 
   (	"IMAGE_AND_LIKE_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"IMAGE_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"POST_NO" NUMBER(10,0), 
	"LIKE_WRITER" VARCHAR2(30) NOT NULL ENABLE, 
	"IMAGE_AND_LIKE_STATE" CHAR(1) NOT NULL ENABLE, 
	 CONSTRAINT "IMAGE_AND_LIKE_PK" PRIMARY KEY ("IMAGE_AND_LIKE_NO") ENABLE, 
	 CONSTRAINT "IMAGE_AND_LIKE_FK" FOREIGN KEY ("POST_NO")
	  REFERENCES  "POST" ("POST_NO") ON DELETE CASCADE ENABLE
   );
   
   INSERT INTO IMAGE_AND_LIKE values(SEQ_IMAGE_AND_LIKE_NO.nextval,'ㅁㄴㅇ.jpg',2,'우씨','1');
   UPDATE IMAGE_AND_LIKE set IMAGE_AND_LIKE_STATE = '0' WHERE post_no = 2;
   
   CREATE TABLE  "COMMENTS" 
   (	"COMMENT_NO" NUMBER NOT NULL ENABLE, 
	"COMMENT_DETAIL" VARCHAR2(400) NOT NULL ENABLE, 
	"COMMENT_WRITER" VARCHAR2(30) NOT NULL ENABLE, 
	"COMMENT_REG_DATE" DATE NOT NULL ENABLE, 
	"POST_NO" NUMBER NOT NULL ENABLE, 
	"TREE_NO" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "COMMENTS_PK" PRIMARY KEY ("COMMENT_NO") ENABLE, 
	 CONSTRAINT "COMMENTS_FK" FOREIGN KEY ("POST_NO")
	  REFERENCES  "POST" ("POST_NO") ENABLE
   );
   
    INSERT INTO COMMENTS values(SEQ_COMMENT_NO.nextval,'댓글내용입니다','작성자입니다',SYSDATE,2,2);
    
    CREATE TABLE  "ACTIVITY_POINT" 
   (	"ACTIVITY_POINT_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"TREE_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"POINT" NUMBER(10,0) NOT NULL ENABLE, 
	"ACTIVITY_DATE" DATE NOT NULL ENABLE, 
	"ACTIVITY_TYPE" CHAR(1) NOT NULL ENABLE, 
	 CONSTRAINT "ACTIVITY_POINT_PK" PRIMARY KEY ("ACTIVITY_POINT_NO") ENABLE, 
	 CONSTRAINT "ACTIVITY_POINT_FK" FOREIGN KEY ("TREE_NO")
	  REFERENCES  "TREE" ("TREE_NO") ON DELETE CASCADE ENABLE
   );
   
    INSERT INTO ACTIVITY_POINT values(SEQ_ACTIVITY_POINT_NO.nextval,23,10,SYSDATE,'1');
   
    SELECT * FROM ACTIVITY_POINT ;
    
    CREATE TABLE  "REPORT" 
   (	"REPORT_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"REPORT_TYPE" CHAR(1) NOT NULL ENABLE, 
	"REPORTED_POST_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"REPORT_STATE" CHAR(100) NOT NULL ENABLE, 
	"REPORTER_TREE_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"REPORTED_TREE_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"REPORT_REG_DATE" DATE NOT NULL ENABLE, 
	 CONSTRAINT "REPORT_PK" PRIMARY KEY ("REPORT_NO") ENABLE
   );
   
   INSERT INTO REPORT values(SEQ_REPORT_NO.nextval,'2',2,'0',2,4,SYSDATE);
   
   SELECT * FROM REPORT ;
   
   
   CREATE TABLE  "BUCKETLIST"
   (	"BUCKETLIST_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"BUCKETLIST_WRITER" VARCHAR2(30) NOT NULL ENABLE, 
	"BUCKETLIST_DETAIL" VARCHAR2(200) NOT NULL ENABLE, 
	"BUCKETLIST_REG_DATE" DATE NOT NULL ENABLE, 
	"STAMP_STATE" CHAR(1) NOT NULL ENABLE, 
	"TREE_NO" NUMBER(10,0) NOT NULL ENABLE, 
	 CONSTRAINT "BUCKETLIST_PK" PRIMARY KEY ("BUCKETLIST_NO") ENABLE, 
	 CONSTRAINT "BUCKETLIST_FK" FOREIGN KEY ("TREE_NO")
	  REFERENCES  "TREE" ("TREE_NO") ON DELETE CASCADE ENABLE
   );
   
   INSERT INTO BUCKETLIST values(SQE_BUCKETLIST_NO.nextval,'작성자입니다','내용입니다',SYSDATE,'0',23);
   
   
     INSERT INTO COMMENTS values(SEQ_COMMENT_NO.nextval,'댓글내용입니다','작성자입니다',SYSDATE,2,21);
   
